org.gradle.jvmargs=-Xmx4096M -Dkotlin.daemon.jvm.options=-Xmx2048M
android.useAndroidX=true
android.enableJetifier=true

# Kotlin JVM target
kotlin.code.style=official
kotlin.jvm.target=17

# Enable modern AGP features
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false
